config/routes.rb
Paxos::Application.routes.draw do
  namespace :admin do
    resources :estudios
    resources :conceptos
    resources :tipo_conceptos
    resources :caso_estados
    resources :tipo_actores
    resources :tipo_procesos
    resources :feriados
    resources :juzgados do
      resources :instancias
    end
    resources :users

    root to: "estudios#index"
  end

  resources :actores
  resources :casos do
    resources :consultas
  end
  resources :documentos
  resources :movimientos

  root to: "actores#index"

  devise_for :admins
  devise_for :users
end

app/models/actor.rb
class Actor < ActiveRecord::Base
  validates :nombre, :tipo_actor_id, :tipo_documento, :documento, presence: true

  scope :alfabeticamente, order("actores.nombre ASC")
  scope :clientes, joins(:tipo_actor).where("tipo_actores.nombre" => "Clientes")

  belongs_to :estudio
  belongs_to :tipo_actor

  delegate :nombre, to: :tipo_actor, prefix: true
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :timeoutable
end

app/models/caso.rb
class Caso < ActiveRecord::Base
  belongs_to :estudio
  belongs_to :tipo_proceso
  belongs_to :user
  belongs_to :instancia

  has_many :caso_actores
  has_many :actores, through: :caso_actores
  has_many :consultas

  validates :estudio, :tipo_proceso_id, :user, :instancia_id, presence: true

  accepts_nested_attributes_for :caso_actores, allow_destroy: true

  scope :ultimos, order("casos.created_at DESC")

  delegate :nombre, to: :tipo_proceso, prefix: true
  delegate :nombre, to: :instancia, prefix: true

  def actores_nombre
    actores.pluck(:nombre).to_sentence
  end
end

app/models/caso_actor.rb
class CasoActor < ActiveRecord::Base
  belongs_to :caso
  belongs_to :actor

  # validates :caso, :actor, presence: true
end

app/models/caso_estado.rb
class CasoEstado < ActiveRecord::Base
  validates :nombre, presence: true, uniqueness: true

  scope :alfabeticamente, order("caso_estados.nombre ASC")
end

app/models/concepto.rb
class Concepto < ActiveRecord::Base
  validates :nombre, presence: true, uniqueness: { scope: :tipo_concepto_id }
  validates :tipo_concepto_id, presence: true

  belongs_to :tipo_concepto

  scope :alfabeticamente, order("conceptos.nombre ASC")

  delegate :nombre, to: :tipo_concepto, prefix: true
end

app/models/consulta.rb
class Consulta < ActiveRecord::Base
  validates :caso, :estudio, presence: true

  belongs_to :caso
  belongs_to :estudio

  scope :ultimas, order("consultas.created_at ASC")
end

app/models/documento.rb
class Documento < ActiveRecord::Base
  validates :actor_id, presence: true

  belongs_to :user
  belongs_to :actor

  scope :ultimos, order("documentos.fecha_entrega DESC")

  delegate :nombre, to: :actor, prefix: true
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
  validates :nombre, presence: true

  scope :alfabeticamente, order("estudios.nombre ASC")

  has_many :actores
  has_many :documentos
  has_many :movimientos
  has_many :casos

  def cuenta_corriente
    @cuenta_corriente ||= movimientos.sum(:importe)
  end
end

app/models/feriado.rb
class Feriado < ActiveRecord::Base
  validates :fecha, presence: true, uniqueness: true
  validates :nombre, presence: true

  scope :crono_desc, order("feriados.fecha DESC")
end

app/models/instancia.rb
class Instancia < ActiveRecord::Base
  validates :nombre, presence: true, uniqueness: { scope: :juzgado_id }

  belongs_to :juzgado

  scope :alfabeticamente, order("instancias.nombre ASC")
end

app/models/juzgado.rb
class Juzgado < ActiveRecord::Base
  validates :nombre, presence: true, uniqueness: true

  has_many :instancias

  scope :sorted, order("juzgados.position ASC")
end

app/models/movimiento.rb
class Movimiento < ActiveRecord::Base
  validates :actor_id, :concepto_id, :importe, :descripcion, presence: true

  belongs_to :user
  belongs_to :actor
  belongs_to :concepto

  scope :ultimos, order("movimientos.fecha DESC")

  delegate :nombre, to: :actor, prefix: true
  delegate :nombre, to: :concepto, prefix: true
  delegate :tipo_concepto, to: :concepto, prefix: true

  before_save :calc_sign

  def show_importe
    importe.to_i * sign
  end

private

  def calc_sign
    self.importe *= sign
  end

  def sign
    (concepto && concepto_tipo_concepto.nombre == "Haber") ? 1 : -1
  end
end

app/models/tipo_actor.rb
class TipoActor < ActiveRecord::Base
  validates :nombre, presence: true, uniqueness: true

  scope :alfabeticamente, order("tipo_actores.nombre ASC")
end

app/models/tipo_concepto.rb
class TipoConcepto < ActiveRecord::Base
  validates :nombre, presence: true, uniqueness: true

  scope :alfabeticamente, order("tipo_conceptos.nombre ASC")
end

app/models/tipo_proceso.rb
class TipoProceso < ActiveRecord::Base
  validates :nombre, presence: true, uniqueness: true

  scope :alfabeticamente, order("tipo_procesos.nombre ASC")
end

app/models/user.rb
class User < ActiveRecord::Base
  devise  :database_authenticatable, :recoverable, :rememberable,
          :trackable, :validatable, :invitable

  validates :nombre, :apellido, :estudio, presence: true

  belongs_to :estudio

  scope :alfabeticamente, order("users.apellido ASC, users.nombre ASC")

  delegate :nombre, to: :estudio, prefix: true

  def nombre_completo
    [nombre, apellido].join(", ")
  end
end

app/controllers/actores_controller.rb
class ActoresController < DashboardController
  has_scope :alfabeticamente, default: true, type: :boolean

private

  def begin_of_association_chain
    current_estudio
  end

  def resource_params
    return [] if request.get?
    [ params.require(:actor).permit(:nombre, :tipo, :tipo_documento, 
      :documento, :domicilio, :telefono, :fecha_nacimiento, :estado_civil,
      :casado_con, :email, :tipo_actor_id)
    ]
  end
end

app/controllers/casos_controller.rb
class CasosController < DashboardController
  has_scope :ultimos, default: true, type: :boolean

  def create
    build_resource
    resource.user = current_user

    super
  end

private

  def begin_of_association_chain
    current_estudio
  end

  def resource_params
    return [] if request.get?
    [ params.require(:caso).permit(:tipo_proceso_id, :instancia_id,
      :caratula, :observacion, :numero_carpeta, :fecha_inicio, :fecha_fin,
      :numero_archivo, caso_actores_attributes: [ :actor_id, :_destroy ])
    ]
  end
end

app/controllers/consultas_controller.rb
class ConsultasController < DashboardController
  has_scope :ultimas, default: true, type: :boolean

  belongs_to :caso

  def create
    build_resource
    resource.estudio = @current_estudio

    super
  end

  private

  def resource_params
    return [] if request.get?
    [ params.require(:consulta).permit(:fecha, :titulo, :descripcion, 
      :fecha_presentacion, :con_vencimiento) ]
  end
end

app/controllers/crud_controller.rb
class CrudController < InheritedResources::Base
  has_scope :page, default: 1
  has_scope :per,  default: 9999

  include InheritedResources::DSL

  create!(notice: I18n.t("create_success")) { collection_url }
  update!(notice: I18n.t("create_success")) { collection_url }
  destroy!(notice: I18n.t("destroy_success")) { collection_url }
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def actores_for_select
    @current_estudio.actores.includes(:tipo_actor).alfabeticamente.
      group_by{ |a| a.tipo_actor_nombre }.
      map { |tipo_actor, actores|
        [tipo_actor, actores.map{|a| [a.nombre, a.id] } ]
      }
  end
end

app/views/casos/_caso.slim
tr
  td= caso.actores_nombre
  td= caso.tipo_proceso_nombre
  td= caso.instancia_nombre
  td= caso.caratula
  td= caso.fecha_inicio
  td= caso.fecha_fin
  td.actions
    = link_to "Consultas", caso_consultas_path(caso), class: "btn btn-info btn-small"
    |  
    = render "edit_destroy", row: caso

app/views/casos/_form.slim
= simple_nested_form_for resource, html: { class: "stdform" } do |f|
  .widget
    h4.widgettitle Información del caso
    .widgetcontent
      = f.input :tipo_proceso_id, collection: TipoProceso.alfabeticamente, label_method: "nombre", input_html: { class: "chzn-select input-xxlarge" }
      = f.input :instancia_id, collection: Instancia.alfabeticamente, label_method: "nombre", input_html: { class: "chzn-select input-xxlarge" }
      = f.input :caratula, input_html: { class: "input-xxlarge" }
      = f.input :observacion, input_html: { class: "input-xxlarge" }
      = f.input :numero_carpeta, input_html: { class: "input-xxlarge" }
      = f.input :numero_archivo, input_html: { class: "input-xxlarge" }

  .widget
    h4.widgettitle Fechas
    .widgetcontent
      = f.input :fecha_inicio, as: :date, input_html: { class: "input-small" }
      = f.input :fecha_fin, as: :date, input_html: { class: "input-small" }

  .widget
    h4.widgettitle Actores
    .widgetcontent
      = f.fields_for :caso_actores do |caso_actor_form|
        .control-group
          = caso_actor_form.label :actor_id, "Actor", class: "control-label"
          .controls
            = caso_actor_form.select :actor_id, actores_for_select, {}, { class: "chzn-select input-xxlarge" }
            = caso_actor_form.link_to_remove "Eliminar"
      = f.link_to_add "Agregar actor", :caso_actores, class: "btn btn-info"

  .stdformbutton= render "resource_actions", f: f

app/views/casos/_header.slim
tr
  th Actores
  th Tipo Proceso
  th Instancia
  th Caratula
  th Fecha de inicio
  th Fecha de fin
  th

app/views/consultas/_breadcrumb.slim
ul.breadcrumbs
  li
    = link_to %(<i class="icon-home"></i> #{@current_estudio.nombre}).html_safe, root_path
    span.separator
  li
    = link_to parent.caratula, edit_caso_path(parent)
    span.separator
  = link_to t("#{controller_name}.#{action_name}"), collection_path, class: "current"

app/views/consultas/_consulta.slim
tr
  td= consulta.fecha
  td= consulta.titulo
  td= consulta.descripcion
  td= consulta.fecha_presentacion
  td= consulta.con_vencimiento
  td.actions= render "edit_destroy", row: consulta

app/views/consultas/_form.slim
= simple_form_for [parent, resource], html: { class: "stdform" } do |f|
  .widget
    h4.widgettitle Información de la consulta
    .widgetcontent
      = f.input :fecha, as: :date, input_html: { class: "input-small" }
      = f.input :titulo, input_html: { class: "input-xxlarge" }
      = f.input :descripcion, input_html: { class: "input-xxlarge" }
      = f.input :fecha_presentacion, as: :date, input_html: { class: "input-small" }
      = f.input :con_vencimiento

      .stdformbutton= render "resource_actions", f: f

app/views/consultas/_header.slim
tr
  th Fecha
  th Titulo
  th Descripcion
  th Fecha de presentacion
  th Con vencimiento
  th 